### PR TITLE
Remove ridley as a dep of Berkshelf

### LINKED ISSUE #1345: berkshelf 3.1.5 can't upload its own vendored cookbooks
I used berks vendor to dump a cookbooks directory for my environment, and zipped it up for deploying/rolling back.

If I set BERKSHELF_PATH to a new directory 'c:/path/to/cookbooks', and unzip the vendored cookbook files into that new directory, and 'berks upload --berksfile c:\path\to\cookbooks\my_env_cb\Berksfile', I get

> An error occurred while reading the Berksfile:
> 
>   Could not open or read: 'c:/path/to/cookbooks/my_env_cb/metadata.rb'

Sure enough, there's no metadata.rb there: the metadata has been ripped to .json already.

If it hasn't been fixed already, can berks please prefer its own vendored metadata.json when uploading?
This is with chefdk 0.3.2-1 on windows.

### LINKED ISSUE #1536: metadata precedence
I was pulling my hair out trying to resolve a dependency issue, and it turned out that the problem was due to a rogue cookbook that had _both_ a metadata.rb and a metadata.json, each at different versions.  The metadata.rb was at 0.6.6, the metadata.json at 0.6.3.  When I'd do a `berks install`, things would look good, but any subsequent command would fail, complaining that 0.6.3 of the cookbook was not available.

I know this isn't common, but if a warning can be thrown if both files exist, or if metadata.rb (or metadata.json) was referenced _always_, then that'd be ideal.  I think throwing a warning (or failing entirely) is ideal, just like with cookbooks without the name attribute in the metadata.

### LINKED ISSUE #1651: berks vendor should copy metadata.rb also
Hi, when we launch berks vendor, it's create metadata.json and not copied metadata.rb.  After that we launch kitchen commands like converge and got failures. It's because kitchen launch berks and parse Berksfile which consist metadata method. This method required metadata.rb

Could you please copy metadata.rb also when launch command berks vendor.
Thanks

### PR DESCRIPTION
**Pull request by lamont-granquist**
note that there's some transitional copypasta of the faraday middleware from ridley into berkshelf here.  this is an incremental change.  removing faraday is another step.  removing buff-config is another step.

note that this will be a deliberate breaking change for two reasons:

- recommends is dropped and is no longer synonymous with dependencies -- and [RFC-085](https://github.com/chef/chef-rfc/blob/master/rfc085-remove-unused-metadata.md) basically mandates this and foodcritic has warned for over two years about this: https://github.com/Foodcritic/foodcritic/pull/309.  These are the kinds of issues it causes end-users to have berks using this while chef-client and server silently ignore it:  ovaistariq/cookbook-multipath#9

- metadata.rb is now shipped alongside metadata.json and no longer stripped from packaged cookbooks.   prior issues:  #1652, #1660 also chef/chef#5750 and chef/chef-zero#251.  metadata.json should always be favored over metadata.rb which is consistent with chef-client / chef-zero / chef-fs behavior now.  there may be compatibility issues for some use cases with chef-client versions prior to 12.19.33 ( chef >= 13.0.0 should be fully supported)

closes #1352
closes #1345
closes #1651
closes #1536

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@chef/client-core this is reviewable finally

File: lib/berkshelf/cached_cookbook.rb [hunk 1]
```diff
@@ -15,26 +20,71 @@ def from_store_path(path)
...
       def loaded_cookbooks
         @loaded_cookbooks ||= {}
       end
     end
 
+    attr_accessor :metadata
+    attr_accessor :path
+    attr_accessor :cookbook_version
+
+    # name and metadata are now ignored and should be removed
```
Comment (danielsdeleo) [inline lib/berkshelf/cached_cookbook.rb]: Out of curiosity, are we supporting "library" usage of berks, et. al? I get that we have to do that in Chef Client but in ChefDK (outside of a handful of classes) and here we should try to limit the places where we promise ruby-level compat. Probably a topic for another venue tho.

File: lib/berkshelf/middleware/follow_redirects.rb [hunk 2]
```diff
@@ -0,0 +1,135 @@
...
+    # Borrowed and modified from:
+    # {https://github.com/lostisland/faraday_middleware/blob/master/lib/faraday_middleware/response/follow_redirects.rb}
+    #
+    # Public: Follow HTTP 301, 302, 303, and 307 redirects for GET, PATCH, POST,
+    # PUT, and DELETE requests.
+    #
+    # This middleware does not follow the HTTP specification for HTTP 302, by
+    # default, in that it follows the improper implementation used by most major
+    # web browsers which forces the redirected request to become a GET request
+    # regardless of the original request method.
```
Comment (danielsdeleo) [inline lib/berkshelf/middleware/follow_redirects.rb]: Should we just force this behavior on? I can't think of a case in the Chef world where switching to GET is what we want.

File: lib/berkshelf/cached_cookbook.rb (hunk 1 above)
Comment (lamont-granquist) [inline lib/berkshelf/cached_cookbook.rb]: https://github.com/berkshelf/berkshelf#cli-usage

No.

TK should be using mixlib-shellout instead of using it as a library, etc.

File: lib/berkshelf/middleware/follow_redirects.rb (hunk 2 above)
Comment (lamont-granquist) [inline lib/berkshelf/middleware/follow_redirects.rb]: The middleware code here all gets deleted and converted to use `Chef::HTTP::Simple{JSON}` before we ship, and we drop the faraday/httpclient deps and just use Chef::HTTP.  Precisely to not have to think about issues like this twice...

File: lib/berkshelf/cached_cookbook.rb (hunk 1 above)
Comment (lamont-granquist) [inline lib/berkshelf/cached_cookbook.rb]: oh yeah so i should totally do that thing in the comment, that was basically a fixme i didn't fix...

File: lib/berkshelf/middleware/follow_redirects.rb (hunk 2 above)
Comment (danielsdeleo) [inline lib/berkshelf/middleware/follow_redirects.rb]: :100:
